[project]
dependencies = [
  "faker>=37.0.0",
  "httpx>=0.28.1",
  "pymysql>=1.1.2",
  "python-dotenv>=1.2.2",
  "scrapling>=0.4.12",
  "sqlalchemy>=2.0.48",
]
description = "造业务数据"
name = "dbmock"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"

[dependency-groups]
dev = [
  "ruff>=0.15.16",
  "pyright>=1.1.410",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
